apiVersion: v1
data:
  values: |-
    sources:
    - name: my-repository
      interval: 1m
      branch: main
      url: https://github.com/my-repository
      provider: github
      credentials:
        username: fakeuser
        token: faketoken
    kustomizations:
    - name: my-kustomizations
      interval: 1m
      path: "./management-clusters/MC_NAME/organizations/${organization}/workload-clusters/CAPI_WC_NAME_OUT_OF_BAND_FLUX_APP/out-of-band"
      prune: false
      source_name: my-repository
kind: ConfigMap
metadata:
  name: ${cluster_name}-flux-app-user-values
  namespace: org-${organization}
