apiVersion: kustomize.config.k8s.io/v1beta1
buildMetadata: [originAnnotations]
configMapGenerator:
  - files:
    - values=default_config.yaml
    name: ${cluster_id}-nginx-ingress-controller-values
generatorOptions:
  disableNameSuffixHash: true
kind: Kustomization
resources:
  - appcr.yaml
