apiVersion: kustomize.config.k8s.io/v1beta1
buildMetadata: [originAnnotations]
commonLabels:
  giantswarm.io/managed-by: flux
kind: Kustomization
resources:
  # - MC_NAME.gpgkey.enc.yaml
  - WC_NAME.gpgkey.enc.yaml
  # - FROM_TEMPLATE_WC_NAME.gpgkey.enc.yaml
