apiVersion: kustomize.config.k8s.io/v1beta1
buildMetadata: [originAnnotations]
configMapGenerator:
  - behavior: replace
    files:
      - values=override_config.yaml
    name: ${cluster_id}-nginx-ingress-controller-values
generatorOptions:
  disableNameSuffixHash: true
kind: Kustomization
resources:
  - ../../../../apps/nginx-ingress-controller
