name: Basic CI

on: push

jobs:
  basic_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: YAMLLint
        uses: docker://gsoci.azurecr.io/giantswarm/yamllint:1.37.1
        with:
          args: .
